theme: jekyll-theme-minimal
title: Ilya Kutuzov
description: PhD candidate at the Hebrew University of Jerusalem
logo: https://drive.google.com/file/d/16PwhdvDUupwukGSjqGqUl0l-TYz2NLO-/view?usp=sharing
show_downloads: false
